// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type User struct {
	ID    int64     `json:"id"`
	Email string    `json:"email"`
	Role  int       `json:"role"`
	Meta  *UserMeta `json:"meta"`
}

type UserMeta struct {
	Nickname *string `json:"nickname"`
}
